name: numpy-tutorials
channels:
  - conda-forge
dependencies:
  # For running the tutorials
  - numpy
  - scipy
  - matplotlib
  - pandas
  - statsmodels
  # Temporary version limit, see https://github.com/numpy/numpy-tutorials/issues/179
  - imageio<2.28
  # For building the site
  - sphinx<5
  - myst-nb
  - sphinx-book-theme
  - sphinx-copybutton
